services:
  db:
    container_name: core-finance-db-debug
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=core_finance
    ports:
      - "5432:5432"
    volumes:
      - core-finance-db-data-debug:/var/lib/postgresql/data
    restart: always

volumes:
  core-finance-db-data-debug:
    name: core-finance-db-data-debug
